const action = {
  LOGIN_USER: "LOGIN_USER",
  LOGOUT_USER: "LOGOUT_USER",
  VIEW_SIDEBAR: "VIEW_SIDEBAR",
  DELETE_STRAND_TYPE: "DELETE_STRAND_TYPE",
  DELETE_STRAND: "DELETE_STRAND",
  DELETE_SUBJECT_TYPE: "DELETE_SUBJECT_TYPE",
  DELETE_SUBJECT: "DELETE_SUBJECT",
  DELETE_PE_QUESTION: "DELETE_PE_QUESTION",
  DELETE_ASSESSMENT_QUESTION: "DELETE_ASSESSMENT_QUESTION",
  PREPARE_SUBJECT: "PREPARE_SUBJECT",
  SET_CURRENT_QUESTION: "SET_CURRENT_QUESTION",
  TEST: "TEST",
};

export { action };
